# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms_overview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='1'),
        ),
    ]
